
#Mysql database config
spring.datasource.url = jdbc:mysql:///invoiceprocessingsystem
spring.datasource.username=root
spring.datasource.password=vishalya
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#hibernate config
spring.jpa.hibernate.ddl-auto = update 
spring.jpa.show-sql= true

